corrections

diff --git a/config_jupyter b/config_jupyter
--- a/config_jupyter
+++ b/config_jupyter
@@ -1,11 +1,9 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-echo "initialization pgcontents"
-pgcontents init --no-prompt -l ${DATABASE_URL/postgres:/postgresql:} || exit 1
-
+echo "Initializing pgcontents..."
+pgcontents init --no-prompt -l ${DATABASE_URL/postgres:/postgresql:} || echo "Error during the initialization of pgcontents."; exit 1
 echo "pgcontents initialized"
-
 
 echo "Starting JupyterLab on Scalingo"
 
@@ -13,12 +11,6 @@ DB_URL="${DATABASE_URL:-}"
 if [ -z "$DB_URL" ] && [ -n "${SCALINGO_POSTGRESQL_URL:-}" ]; then
   DB_URL="$SCALINGO_POSTGRESQL_URL"
 fi
-
-echo "DATABASE_URL is ${DB_URL:-<unset>}"
-
-
-
-
 
 echo "Starting Jupyter Lab"
 exec jupyter lab \
